### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by Nicolador** [Darkaken/floid-metrics#1]
It would be great to have a payload example for using the Income endpoint.
As i can see there is a new 'parametros'  input that must be added in the payload.

**Comment by Nicolador** [comment]
According to change logs it should be something like this: 
{
    "parametros": 
        {
        "monto_minimo_tranzado": 30000,
        "not_income_words": ["hola"],
        "high_income_words": ["sueldo"],
        "medium_income_words": ["abono"],
        "rut_minimo": 30000000,
        "consecutividad": 1,
        "consecutividad_ingresos": 1,
        "ultimo_mes_a_considerar": 1}
    ,
    "transactions": [
        {
            "date": "2021-04-05",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "635069741",
            "out": 0,
            "in": 5000000,
            "balance": 6831231,
            "id": "720d877df44cca19d88da8fe9db8f0cd1"
        },
        {
            "date": "2021-04-05",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5798515,
            "in": 0,
            "balance": 1032716,
            "id": "f5713e168cc841213b0b6264429c49d01"
        },
        {
            "date": "2021-04-05",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 653208,
            "in": 0,
            "balance": 379508,
            "id": "53230532baf6a7cf6e0c68f2a87d16421"
        },
        {
            "date": "2021-04-06",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "636491912",
            "out": 0,
            "in": 1774000,
            "balance": 2153508,
            "id": "df4ab397a2b0e254358482206044ba1a1"
        },
        {
            "date": "2021-04-19",
            "branch": "PREFISIDO",
            "description": "SEGURO DE DESGRAVAMEN LINEA SOBREGIRO",
            "doc_number": "708",
            "out": 11780,
            "in": 0,
            "balance": 2141728,
            "id": "d6bcc4f3533f7139bf4bd71410804ee81"
        },
        {
            "date": "2021-04-26",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "643724398",
            "out": 0,
            "in": 445419,
            "balance": 2587147,
            "id": "a008ce976dc1aab49b97969cb94cd5581"
        },
        {
            "date": "2021-05-03",
            "branch": "OF CENTRA",
            "description": "ABONO TERCEROS 15656390-0 A.SANHUEZA BAR",
            "doc_number": "479746243",
            "out": 0,
            "in": 4473599,
            "balance": 7060746,
            "id": "d2345df963c4feeeb4def547f279a2451"
        },
        {
            "date": "2021-05-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 4473599,
            "in": 0,
            "balance": 2587147,
            "id": "7b5ae326d5bd311e990df05d0de519fc1"
        },
        {
            "date": "2021-05-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 1353214,
            "in": 0,
            "balance": 1233933,
            "id": "270d36eb38c7f3cd1d6090f31c68dc501"
        },
        {
            "date": "2021-05-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "647224429",
            "out": 0,
            "in": 1353214,
            "balance": 2587147,
            "id": "b032f58a4ecd8d5edd2f60b67b9bfab21"
        },
        {
            "date": "2021-06-02",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "661589383",
            "out": 0,
            "in": 2559000,
            "balance": 5146147,
            "id": "4038f7e96b4dc0c40534bb5d1bc2ebd21"
        },
        {
            "date": "2021-06-02",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5116893,
            "in": 0,
            "balance": 29254,
            "id": "765a0cba1d12824472432a67dadaaed31"
        },
        {
            "date": "2021-06-10",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "665632539",
            "out": 0,
            "in": 2587000,
            "balance": 2616254,
            "id": "14a96ef0718136dfc1817f569522aa961"
        },
        {
            "date": "2021-07-01",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "674184410",
            "out": 0,
            "in": 3815000,
            "balance": 6431254,
            "id": "e525847b12ab30af07d264f6bf66e3a61"
        },
        {
            "date": "2021-07-01",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5745000,
            "in": 0,
            "balance": 686254,
            "id": "00b888303d93210f1069afbbb399f5591"
        },
        {
            "date": "2021-07-01",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 69168,
            "in": 0,
            "balance": 617086,
            "id": "60263abe401c7e25676b8097266c2ff01"
        },
        {
            "date": "2021-07-01",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 23,
            "in": 0,
            "balance": 617063,
            "id": "e19849afd569ead600a8ff264dfa95f71"
        },
        {
            "date": "2021-07-07",
            "branch": "PREFISIDO",
            "description": "ABONO DE CREDITO 29600179865",
            "doc_number": "29600179865",
            "out": 0,
            "in": 19000000,
            "balance": 19617063,
            "id": "9843f6ac34f4b09ebddd95db677d0d551"
        },
        {
            "date": "2021-07-08",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "677825220",
            "out": 0,
            "in": 2346000,
            "balance": 21963063,
            "id": "e43fb0323178b44ba21dcfb4502132491"
        },
        {
            "date": "2021-07-08",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "677826135",
            "out": 0,
            "in": 250000,
            "balance": 22213063,
            "id": "4e549ea520cd4fe68a76b146c38e25ff1"
        },
        {
            "date": "2021-07-08",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 250000,
            "in": 0,
            "balance": 21963063,
            "id": "04c9b9c5b7c31756ea024f90cea0151e1"
        },
        {
            "date": "2021-07-14",
            "branch": "OF CENTRA",
            "description": "CHEQUE COBRADO POR OTRO BANCO",
            "doc_number": "295297",
            "out": 20498094,
            "in": 0,
            "balance": 1464969,
            "id": "fee3667b92987bbb3f7fde584e0f0d951"
        },
        {
            "date": "2021-07-15",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "681108835",
            "out": 0,
            "in": 1500000,
            "balance": 2964969,
            "id": "8a194c7716fdec0c0850750397d4dbe41"
        },
        {
            "date": "2021-07-26",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "684353833",
            "out": 0,
            "in": 353866,
            "balance": 3318835,
            "id": "8cbd3804370fa718b0f3133f0f85a6e31"
        },
        {
            "date": "2021-08-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "689235946",
            "out": 0,
            "in": 4826867,
            "balance": 8145702,
            "id": "bdb4a9acd64975bdedafc9ed6ee5e87e1"
        },
        {
            "date": "2021-08-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 4178000,
            "in": 0,
            "balance": 3967702,
            "id": "45fdc6d3dcd69337bdd2dcb4762c1caa1"
        },
        {
            "date": "2021-08-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER A G.OL",
            "doc_number": "513701066",
            "out": 648000,
            "in": 0,
            "balance": 3319702,
            "id": "9b86120547b9a853dd96f88e236636001"
        },
        {
            "date": "2021-08-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER A G.OL",
            "doc_number": "513704451",
            "out": 1000000,
            "in": 0,
            "balance": 2319702,
            "id": "3ad20950f43c4161e1f969d203586ace1"
        },
        {
            "date": "2021-08-30",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "700833070",
            "out": 0,
            "in": 389087,
            "balance": 2708789,
            "id": "8c8b597a101469e28c0cb49155afe52a1"
        },
        {
            "date": "2021-09-02",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "703056698",
            "out": 0,
            "in": 2500000,
            "balance": 5208789,
            "id": "a0452df1c992c6d76573434c7b8a55041"
        },
        {
            "date": "2021-09-02",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5193209,
            "in": 0,
            "balance": 15580,
            "id": "1b80e135b79f4f104ed6cd6bad146a1c1"
        },
        {
            "date": "2021-09-13",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "708750446",
            "out": 0,
            "in": 2708000,
            "balance": 2723580,
            "id": "0f082e921f8ef75edbc5bde957454e9e1"
        },
        {
            "date": "2021-09-24",
            "branch": "PREFISIDO",
            "description": "PAGO CREDITO D29600179865 001/060",
            "doc_number": "29600179865",
            "out": 566644,
            "in": 0,
            "balance": 2156936,
            "id": "55666336110953b0422d851f6f508cb61"
        },
        {
            "date": "2021-10-04",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "718355885",
            "out": 0,
            "in": 500000,
            "balance": 2656936,
            "id": "2ec8457479b3450bc0d3e088edb56ac01"
        },
        {
            "date": "2021-10-04",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "718357244",
            "out": 0,
            "in": 4500000,
            "balance": 7156936,
            "id": "1f6488b98dce1ed4804f998a9cc2b9c21"
        },
        {
            "date": "2021-10-04",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 4122799,
            "in": 0,
            "balance": 3034137,
            "id": "ea1d053f7060e6b1ccb6ee868483380c1"
        },
        {
            "date": "2021-10-25",
            "branch": "PMCF",
            "description": "PAGO CREDITO D47799900891 002/060",
            "doc_number": "47799900891",
            "out": 587311,
            "in": 0,
            "balance": 2446826,
            "id": "39e97db2dadee313d45561bffd5eb5641"
        },
        {
            "date": "2021-11-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "732892874",
            "out": 0,
            "in": 4739000,
            "balance": 7185826,
            "id": "16a12de3c6ffca533bd53a93450fd3041"
        },
        {
            "date": "2021-11-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 4153000,
            "in": 0,
            "balance": 3032826,
            "id": "a813e8b8c6295a11d877048fa0c249a51"
        },
        {
            "date": "2021-11-22",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 758000,
            "in": 0,
            "balance": 2274826,
            "id": "cec73e33b71f7f7c6aed3b4ef45ea9c21"
        },
        {
            "date": "2021-11-22",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "742320185",
            "out": 0,
            "in": 758000,
            "balance": 3032826,
            "id": "a6273faf40432dda2b0c251d1db0c3241"
        },
        {
            "date": "2021-11-24",
            "branch": "PPPB",
            "description": "PAGO CREDITO D66199905313 003/060",
            "doc_number": "66199905313",
            "out": 587311,
            "in": 0,
            "balance": 2445515,
            "id": "cfbee68e84cd54eefd55a8f344cbef531"
        },
        {
            "date": "2021-12-01",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "747213454",
            "out": 0,
            "in": 2649000,
            "balance": 5094515,
            "id": "826b942e62fa21110b790f3b1dabc34c1"
        },
        {
            "date": "2021-12-01",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5093000,
            "in": 0,
            "balance": 1515,
            "id": "597a78b5da298d8f90579b23457337ee1"
        },
        {
            "date": "2021-12-13",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "753607609",
            "out": 0,
            "in": 3432000,
            "balance": 3433515,
            "id": "fbbf8fbeeff4786e983999a0003bda2c1"
        },
        {
            "date": "2021-12-22",
            "branch": "OF CENTRA",
            "description": "ABONO SALDO A FAVOR EN TARJETA DE CREDIT",
            "doc_number": "1332",
            "out": 0,
            "in": 1277,
            "balance": 3434792,
            "id": "414b54c922283d87fe266ee5a859afee1"
        },
        {
            "date": "2021-12-24",
            "branch": "PPPB",
            "description": "PAGO CREDITO D66199905313 004/060",
            "doc_number": "66199905313",
            "out": 587311,
            "in": 0,
            "balance": 2847481,
            "id": "352cadae19dfac3431e49a1c0d629e6a1"
        },
        {
            "date": "2022-01-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "764509803",
            "out": 0,
            "in": 2807000,
            "balance": 5654481,
            "id": "cf8cb4d3887212942e538d92e1e156d51"
        },
        {
            "date": "2022-01-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 72094,
            "in": 0,
            "balance": 5582387,
            "id": "5b80793bd83d34172c0456eae4f48ae31"
        },
        {
            "date": "2022-01-03",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 5579222,
            "in": 0,
            "balance": 3165,
            "id": "426cd928e4ad78f8093f54261bb709691"
        },
        {
            "date": "2022-01-03",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "765020842",
            "out": 0,
            "in": 3434000,
            "balance": 3437165,
            "id": "c8b45f8eeac9e141e5e3d3aee49842171"
        },
        {
            "date": "2022-01-21",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "773831765",
            "out": 0,
            "in": 400000,
            "balance": 3837165,
            "id": "d6e8898334818ec79d0de42a188f50b01"
        },
        {
            "date": "2022-01-21",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 400000,
            "in": 0,
            "balance": 3437165,
            "id": "506a7cc9c2f437c829d29faea0a9d6321"
        },
        {
            "date": "2022-01-24",
            "branch": "PPPB",
            "description": "PAGO CREDITO D66199905313 005/060",
            "doc_number": "66199905313",
            "out": 587311,
            "in": 0,
            "balance": 2849854,
            "id": "dcefb40f36025cabeed0dbdc3eebe9151"
        },
        {
            "date": "2022-02-01",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "779167605",
            "out": 0,
            "in": 4000000,
            "balance": 6849854,
            "id": "97c7eabec7e7694b69f313c764d0a72b1"
        },
        {
            "date": "2022-02-01",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 6002672,
            "in": 0,
            "balance": 847182,
            "id": "e8baa0a48da6103b666c81d9547a7d5a1"
        },
        {
            "date": "2022-02-07",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "781546589",
            "out": 0,
            "in": 2589000,
            "balance": 3436182,
            "id": "d31215dfcb0f64aa7bc497cb3b5d4eb01"
        },
        {
            "date": "2022-02-10",
            "branch": "OF CENTRA",
            "description": "TRANSFER A G.OL",
            "doc_number": "587661710",
            "out": 436000,
            "in": 0,
            "balance": 3000182,
            "id": "3bff3df98657e8a6cc27fd1f2c3491e71"
        },
        {
            "date": "2022-02-10",
            "branch": "OF CENTRA",
            "description": "TRANSFER A G.OL",
            "doc_number": "587715939",
            "out": 384000,
            "in": 0,
            "balance": 2616182,
            "id": "88749064899f8d4d3e1aa33fddccfb821"
        },
        {
            "date": "2022-02-24",
            "branch": "PPPB",
            "description": "PAGO CREDITO D66199905313 006/060",
            "doc_number": "66199905313",
            "out": 587311,
            "in": 0,
            "balance": 2028871,
            "id": "288d68291fe6db113d838474e99d12151"
        },
        {
            "date": "2022-02-28",
            "branch": "OF CENTRA",
            "description": "TRANSFER DE G.O",
            "doc_number": "792052999",
            "out": 0,
            "in": 4298000,
            "balance": 6326871,
            "id": "bc874bbac68591a7fbf726e2791a043e1"
        },
        {
            "date": "2022-02-28",
            "branch": "OF CENTRA",
            "description": "PAGO DEUDA TARJETA DE CREDITO",
            "doc_number": "125",
            "out": 4297156,
            "in": 0,
            "balance": 2029715,
            "id": "577c8aa81e7384eebe0cd74092f6dc2d1"
        },
        {
            "date": "2022-03-14",
            "branch": "OF CENTRA",
            "description": "TRANSFER A G.OL",
            "doc_number": "599673037",
            "out": 200000,
            "in": 0,
            "balance": 1829715,
            "id": "5c03731e8152372484bf310c864c57a81"
        },
        {
            "date": "2022-03-14",
            "branch": "OF CENTRA",
            "description": "CARGO DEUDA TARJETA CREDITO MASTERCARD",
            "doc_number": "1156",
            "out": 4795,
            "in": 0,
            "balance": 1824920,
            "id": "77c7c0139485611062bb500e6477dfa81"
        },
        {
            "date": "2022-03-24",
            "branch": "PPPB",
            "description": "PAGO CREDITO D66199905313 007/060",
            "doc_number": "66199905313",
            "out": 587311,
            "in": 0,
            "balance": 1237609,
            "id": "7b7049464d95b0ea963aad84cd330a701"
        }
    ]
}

**Comment by Darkaken** [comment]
I uploaded an example request for the API with the correct input structure
